embederator.embederator_type.*:
  type: config_entity
  label: 'Embederator Type settings'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    uuid:
      type: stype
      label: 'UUID'
    label:
      type: label
      label: 'Label'
    use_ssi:
      type: boolean
      label: 'Use server-side include (vs. markup)'
    embed_markup:
      type: mapping
      label: 'Markup'
      mapping:
        value:
          type: string_long
          label: 'Value'
        format:
          type: string
          label: 'Format'
    embed_url:
      type: string
      label: 'URL for server-side markup include'
    wrapper_class:
      type: string
      label: 'Wrapper class for template'

field.formatter.settings.embederator_default:
  type: mapping
  label: 'Embederator formatter settings'
  mapping:
    append_unique_id:
      type: boolean
      label: 'Append unique DOM ID'
    nullify_cache:
      type: boolean
      label: 'Force zero-length cache'
